#!/bin/bash
# Auto Monitoring Script

echo "📊 Auto Monitoring - Ultimate Assistant Mode"

PROJECT_NAME=$1
PROJECT_EMAIL=${USER_EMAIL:-"user@email.com"}

if [ -z "$PROJECT_NAME" ]; then
    echo "❌ Project name is required"
    exit 1
fi

echo "📋 Monitoring project: $PROJECT_NAME"
echo "📧 Email: $PROJECT_EMAIL"

# Check project status
cd "$PROJECT_NAME"

# Check if project is running
if pgrep -f "$PROJECT_NAME" > /dev/null; then
    STATUS="Running"
    echo "✅ Project is running"
else
    STATUS="Stopped"
    echo "❌ Project is stopped"
fi

# Check disk usage
DISK_USAGE=$(du -sh . | cut -f1)
echo "💾 Disk usage: $DISK_USAGE"

# Check memory usage
MEMORY_USAGE=$(ps aux | grep "$PROJECT_NAME" | awk '{sum+=$6} END {print sum/1024 " MB"}')
echo "🧠 Memory usage: $MEMORY_USAGE"

# Generate monitoring report
cat > "monitoring-report-$(date +%Y%m%d).md" << EOL
# Monitoring Report - $PROJECT_NAME

**Date**: $(date)
**Status**: $STATUS
**Disk Usage**: $DISK_USAGE
**Memory Usage**: $MEMORY_USAGE

## Performance Metrics
- **Uptime**: $(uptime)
- **Load Average**: $(cat /proc/loadavg)
- **Disk Space**: $(df -h . | tail -1)

## Recommendations
- Monitor disk usage regularly
- Check memory consumption
- Review performance metrics

---
*Generated by Ultimate Assistant - $PROJECT_EMAIL*
EOL

echo "✅ Monitoring report generated"

# Send monitoring email
echo "📧 Sending monitoring report to $PROJECT_EMAIL"
mail -s "Ultimate Assistant: $PROJECT_NAME Monitoring Report" "$PROJECT_EMAIL" < "monitoring-report-$(date +%Y%m%d).md"

echo "🎉 Monitoring completed for $PROJECT_NAME!"
echo "📧 Report sent to $PROJECT_EMAIL"
