name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Upload lint logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-logs
          path: ./logs/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --silent

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: ./dist/
          retention-days: 7

  figma-reuse:
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check Figma reuse
        run: bash scripts/check-figma-multi.sh . 80

      - name: Upload figma analysis
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: figma-analysis
          path: ./artifacts/
          retention-days: 7

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: figma-logs
          path: ./logs/
          retention-days: 7
